// RobotBuilder Version: 2.0ouboule n
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

//Alex owns this code


#include "DriveTrain.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "../Commands/DriveTrainCommand.h"
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

DriveTrain::DriveTrain() : Subsystem("DriveTrain") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    motorRB = RobotMap::driveTrainmotorRB;
    motorRF = RobotMap::driveTrainmotorRF;
    motorLB = RobotMap::driveTrainmotorLB;
    motorLF = RobotMap::driveTrainmotorLF;
    robotdrive = RobotMap::driveTrainrobotdrive;
    testmotor = RobotMap::driveTraintestmotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    i = 0;
}

void DriveTrain::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        SetDefaultCommand(new DriveTrainCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

void DriveTrain::drive(Joystick* joystick)
{
	robotdrive->ArcadeDrive(joystick->GetY(), -joystick->GetX()*0.8);
}

void DriveTrain::settestmotor(double n)
{
	testmotor->Set(n);
	SmartDashboard::PutNumber("Analog In", testmotor->GetAnalogInRaw());
	SmartDashboard::PutNumber("settestmotor runs", i);
}
// Put methods for controlling this subsystem
// here. Call these from Commands.

