// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "AutoChivel.h"
#include "AutoDriveCommand.h"
#include "Commands/CommandGroup.h"
#include "TurnToGyroCommand.h"
#include "ActuateDartCommand.h"
#include "GetDown.h"

AutoChivel::AutoChivel() {

	AddSequential(new AutoDriveCommand(0.5, 1, 0));
	//Drives forward 50%, for 1 second, no turn
	AddSequential(new AutoDriveCommand(0, 0, 0));
	//Drives forward 0% (stops), instantly times out, no turn
	AddSequential(new GetDown());
	//lowers ramp for .25 seconds and lowers dart to bottom POT value
	AddSequential(new AutoDriveCommand(1, 1, 0));
	//drives over the wibbly wobblies at full power for 1 seconds
	AddSequential(new AutoDriveCommand(0, 0, 0));
	//stop the robot
 }

