/*
 * AutoPortipulis.h
 *
 *  Created on: Mar 1, 2016
 *      Author: maxar
 */

#ifndef SRC_COMMANDS_AUTOPortipulis_H_
#define SRC_COMMANDS_AUTOPortipulis_H_

#include "Commands/CommandGroup.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class AutoPortipulis: public CommandGroup {
public:

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	AutoPortipulis();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

private:

};

#endif
