/*
 * AutoRamparts.h
 *
 *  Created on: Mar 3, 2016
 *      Author: maxar
 */

#ifndef SRC_COMMANDS_AUTORAMPARTS_H_
#define SRC_COMMANDS_AUTORAMPARTS_H_

#include "Commands/Subsystem.h"
#include "../Robot.h"
#include "Commands/CommandGroup.h"
class AutoRamparts: public Command {
public:
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	AutoRamparts();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();

	double pos, done;
private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLES


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLES
};




#endif /* SRC_COMMANDS_AUTORAMPARTS_H_ */
