// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "AutoShoot.h"
#include "AutoDriveCommand.h"
#include "Commands/CommandGroup.h"
#include "TurnToGyroCommand.h"
#include "ActuateDartCommand.h"
#include "GetDown.h"
#include "AutoAim.h"
#include "AutoLaunchCommand.h"
#include "LaunchCommand.h"

AutoShoot::AutoShoot() {
	AddSequential(new AutoDriveCommand(.5, 2, 0));
	//Drives forward 50%, for 2 second, no turn
	AddSequential(new AutoDriveCommand(0, 0, 0));
	//Drives forward 0% (stops), instantly times out, no turn
	AddSequential(new AutoAim());
	//stops robot
	AddSequential(new AutoLaunchCommand(true));
	//spins up the launcher
	AddSequential(new LaunchCommand());
	//launches the ball
	AddSequential(new AutoLaunchCommand(false));
	//stops the launcher
 }

