// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "AutoDriveCommand.h"
#include "DistanceOverTimeCG.h"
#include <Commands/WaitCommand.h>


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

DistanceOverTimeCG::DistanceOverTimeCG() {
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
     // Add Commands here:
    // e.g. AddSequential(new Command1());
    //      AddSequential(new Command2());
    // these will run in order.

    // To run multiple commands at the same time,
    // use AddParallel()
    // e.g. AddParallel(new Command1());
    //      AddSequential(new Command2());
    // Command1 and Command2 will run in parallel.

    // A command group will require all of the subsystems that each member
    // would require.
    // e.g. if Command1 requires chassis, and Command2 requires arm,
    // a CommandGroup containing them would require both the chassis and the
    // arm.

	AddSequential(new AutoDriveCommand(0.5, 0, 1));
	//Drives forward 50%, no turn, for 1 second
	AddSequential(new AutoDriveCommand(0, 0, 0));
	//Drives forward 0% (stops), no turn, instantly times out (runs once)
	AddSequential(new WaitCommand(5));
	//Waits for 5 seconds
 }
