// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "TurnToGyroCommand.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

TurnToGyroCommand::TurnToGyroCommand(double gyroValue, double error, double timeout): Command() {
    m_gyroValue = gyroValue;
    m_error = error;
    m_timeout = timeout;
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveTrain.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void TurnToGyroCommand::Initialize() {
	SetTimeout(m_timeout);
	if(m_gyroValue < 0)
		Robot::driveTrain->driveFromValues(0, 0.9);
	else
		Robot::driveTrain->driveFromValues(0, -0.9);
}

// Called repeatedly when this Command is scheduled to run
void TurnToGyroCommand::Execute() {
}

// Make this return true when this Command no longer needs to run execute()
bool TurnToGyroCommand::IsFinished() {
    return abs(Robot::driveTrain->GetGyroAngle() - m_gyroValue) <= m_error
    		|| IsTimedOut();
}

// Called once after isFinished returns true
void TurnToGyroCommand::End() {
	Robot::driveTrain->driveFromValues(0, 0);
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void TurnToGyroCommand::Interrupted() {

}
